# Generated by Django 4.2.2 on 2023-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название Задания')),
                ('anons', models.CharField(max_length=250, verbose_name='О задании')),
                ('phope', models.CharField(max_length=11, verbose_name='Телефон для связи с вами')),
                ('prise', models.CharField(max_length=15, verbose_name='Цена')),
                ('full_text', models.TextField(verbose_name='Задания')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Задания',
                'verbose_name_plural': 'Задании',
            },
        ),
    ]
