# Generated by Django 4.2.3 on 2023-08-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0008_post_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
