# Generated by Django 4.2.4 on 2023-08-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0010_articles_author_articles_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
