# Generated by Django 4.1.10 on 2023-08-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0011_remove_articles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=25, verbose_name='О задании'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=35, verbose_name='Название Задания'),
        ),
    ]
