# Generated by Django 4.1.10 on 2023-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0012_alter_articles_anons_alter_articles_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Messnegr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_messages', models.TextField(verbose_name='Сообщения')),
                ('name_user', models.CharField(max_length=15, verbose_name='Ваше Имя')),
            ],
        ),
    ]
