# Generated by Django 4.1.10 on 2023-08-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0013_user_messnegr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Messnegr',
        ),
    ]
