# Generated by Django 4.1.10 on 2023-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0027_alter_profile_profile_picture_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/tasks_app/img/logo.jpg', null=True, upload_to='', verbose_name='Изображения'),
        ),
    ]
