# Generated by Django 4.1.10 on 2023-08-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0028_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
