# Generated by Django 4.2.5 on 2023-09-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0030_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='profile_pictures', verbose_name='Изображения'),
        ),
    ]
