# Generated by Django 4.2.5 on 2023-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0031_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/tasks_app/img/logo.jpg', null=True, upload_to='', verbose_name='Изображения'),
        ),
    ]
