# Generated by Django 4.2.5 on 2023-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0038_alter_articles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_picture.jpg', null=True, upload_to='media/profile_pictures', verbose_name='Изображения'),
        ),
    ]
