# Generated by Django 4.2.5 on 2023-09-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0039_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_app_user.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_app_user.articles')),
            ],
        ),
    ]
