# Generated by Django 4.2.5 on 2023-09-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0041_remove_comment_post_comment_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
