# Generated by Django 4.2.6 on 2023-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0045_conversation_conversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
