# Generated by Django 4.2.7 on 2023-12-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app_user', '0049_remove_profile_user_delete_comment_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
